

LOAD DATA LOCAL INFILE ‘class.csv’ INTO TABLE Class FIELDS TERMINATED BY ‘,’;
LOAD DATA LOCAL INFILE ‘instructor.csv’ INTO TABLE Instructor FIELDS TERMINATED BY ‘,’;
LOAD DATA LOCAL INFILE ‘question_evaluation.csv’ INTO TABLE Question_Evaluation FIELDS TERMINATED BY ‘,’;
LOAD DATA LOCAL INFILE ‘question.csv’ INTO TABLE Question FIELDS TERMINATED BY ‘,’;
LOAD DATA LOCAL INFILE ‘student_class.csv’ INTO TABLE Student_Class FIELDS TERMINATED BY ‘,’;
LOAD DATA LOCAL INFILE ‘student.csv’ INTO TABLE Student FIELDS TERMINATED BY ‘,’;